<?xml version="1.0" encoding="Windows-1250"?>
<!DOCTYPE schema [
<!ELEMENT schema (scale,left,top,width,height,id,name,comment,(entity*,atribute*,relation*,unique*,cardinality*,strong*)*)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT left (#PCDATA)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT entity (left,top,width,height,id,name,comment)>
<!ELEMENT atribute (left,top,width,height,id,name,comment,datatype,arbitrary,(ent|rel))>
<!ELEMENT relation (left,top,width,height,id,name,comment)>
<!ELEMENT unique (left,top,width,height,id,name,comment,ent,atr*,primary)>
<!ELEMENT cardinality (left,top,width,height,id,name,comment,ent,rel,arbitrary,multi,glue)>
<!ELEMENT strong (left,top,width,height,ent,uni)>
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT arbitrary (#PCDATA)>
<!ELEMENT ent (#PCDATA)>
<!ELEMENT rel (#PCDATA)>
<!ELEMENT atr (#PCDATA)>
<!ELEMENT primary (#PCDATA)>
<!ELEMENT multi (#PCDATA)>
<!ELEMENT glue (#PCDATA)>
<!ELEMENT uni (#PCDATA)>
]>
<schema>
	<scale>1.0</scale>
	<left>0</left>
	<top>0</top>
	<width>2500</width>
	<height>2500</height>
	<id>119</id>
	<name>Schema</name>
	<comment></comment>
	<entity>
		<left>345</left>
		<top>190</top>
		<width>85</width>
		<height>39</height>
		<id>98</id>
		<name>Osetruje</name>
		<comment></comment>
	</entity>
	<unique>
		<left>309</left>
		<top>202</top>
		<width>10</width>
		<height>10</height>
		<id>104</id>
		<name></name>
		<comment></comment>
		<ent>98</ent>
		<primary>true</primary>
	</unique>
	<entity>
		<left>346</left>
		<top>245</top>
		<width>85</width>
		<height>39</height>
		<id>100</id>
		<name>zdr_prohlidka</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>450</left>
		<top>185</top>
		<width>89</width>
		<height>13</height>
		<id>103</id>
		<name>datum_prohl</name>
		<comment></comment>
		<datatype>Date</datatype>
		<arbitrary>true</arbitrary>
		<ent>100</ent>
	</atribute>
	<unique>
		<left>450</left>
		<top>260</top>
		<width>10</width>
		<height>10</height>
		<id>105</id>
		<name></name>
		<comment></comment>
		<ent>100</ent>
		<atr>103</atr>
		<primary>true</primary>
	</unique>
	<relation>
		<left>155</left>
		<top>317</top>
		<width>119</width>
		<height>39</height>
		<id>42</id>
		<name>umisteno</name>
		<comment></comment>
	</relation>
	<cardinality>
		<left>114</left>
		<top>285</top>
		<width>103</width>
		<height>29</height>
		<id>43</id>
		<name>vybeh_umisteno</name>
		<comment></comment>
		<ent>23</ent>
		<rel>42</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>154</left>
		<top>370</top>
		<width>96</width>
		<height>29</height>
		<id>44</id>
		<name>umisteno_zvire</name>
		<comment></comment>
		<ent>12</ent>
		<rel>42</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<strong>
		<left>272</left>
		<top>141</top>
		<width>4</width>
		<height>4</height>
		<ent>19</ent>
		<uni>97</uni>
	</strong>
	<strong>
		<left>461</left>
		<top>140</top>
		<width>4</width>
		<height>4</height>
		<ent>71</ent>
		<uni>97</uni>
	</strong>
	<strong>
		<left>311</left>
		<top>172</top>
		<width>4</width>
		<height>4</height>
		<ent>71</ent>
		<uni>104</uni>
	</strong>
	<strong>
		<left>728</left>
		<top>183</top>
		<width>4</width>
		<height>4</height>
		<ent>49</ent>
		<uni>60</uni>
	</strong>
	<strong>
		<left>634</left>
		<top>139</top>
		<width>4</width>
		<height>4</height>
		<ent>71</ent>
		<uni>60</uni>
	</strong>
	<strong>
		<left>451</left>
		<top>303</top>
		<width>4</width>
		<height>4</height>
		<ent>12</ent>
		<uni>105</uni>
	</strong>
	<entity>
		<left>273</left>
		<top>365</top>
		<width>85</width>
		<height>39</height>
		<id>12</id>
		<name>Zvire</name>
		<comment></comment>
	</entity>
	<unique>
		<left>338</left>
		<top>412</top>
		<width>10</width>
		<height>10</height>
		<id>61</id>
		<name></name>
		<comment></comment>
		<ent>12</ent>
		<atr>13</atr>
		<atr>14</atr>
		<primary>true</primary>
	</unique>
	<atribute>
		<left>402</left>
		<top>395</top>
		<width>50</width>
		<height>13</height>
		<id>17</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>403</left>
		<top>415</top>
		<width>61</width>
		<height>13</height>
		<id>14</id>
		<name>dat_nar</name>
		<comment></comment>
		<datatype>Date</datatype>
		<arbitrary>true</arbitrary>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>403</left>
		<top>434</top>
		<width>54</width>
		<height>13</height>
		<id>13</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>310</left>
		<top>441</top>
		<width>59</width>
		<height>13</height>
		<id>16</id>
		<name>potrava</name>
		<comment></comment>
		<datatype>VarChar2(60)</datatype>
		<arbitrary>false</arbitrary>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>293</left>
		<top>458</top>
		<width>52</width>
		<height>13</height>
		<id>109</id>
		<name>puvod</name>
		<comment></comment>
		<datatype>VarChar2(60)</datatype>
		<arbitrary>false</arbitrary>
		<ent>12</ent>
	</atribute>
	<atribute>
		<left>268</left>
		<top>474</top>
		<width>84</width>
		<height>13</height>
		<id>15</id>
		<name>frek_krmeni</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>12</ent>
	</atribute>
	<entity>
		<left>104</left>
		<top>235</top>
		<width>85</width>
		<height>39</height>
		<id>23</id>
		<name>Vybeh</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>214</left>
		<top>250</top>
		<width>76</width>
		<height>13</height>
		<id>107</id>
		<name>max_zvirat</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>23</ent>
	</atribute>
	<atribute>
		<left>215</left>
		<top>201</top>
		<width>49</width>
		<height>13</height>
		<id>24</id>
		<name>c_vyb</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>23</ent>
	</atribute>
	<unique>
		<left>142</left>
		<top>201</top>
		<width>10</width>
		<height>10</height>
		<id>41</id>
		<name></name>
		<comment></comment>
		<ent>23</ent>
		<atr>24</atr>
		<primary>true</primary>
	</unique>
	<atribute>
		<left>214</left>
		<top>232</top>
		<width>50</width>
		<height>13</height>
		<id>110</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(50)</datatype>
		<arbitrary>false</arbitrary>
		<ent>23</ent>
	</atribute>
	<entity>
		<left>510</left>
		<top>123</top>
		<width>99</width>
		<height>39</height>
		<id>71</id>
		<name>Zamestnanec</name>
		<comment></comment>
	</entity>
	<unique>
		<left>600</left>
		<top>100</top>
		<width>10</width>
		<height>10</height>
		<id>75</id>
		<name></name>
		<comment></comment>
		<ent>71</ent>
		<atr>74</atr>
		<primary>true</primary>
	</unique>
	<atribute>
		<left>442</left>
		<top>66</top>
		<width>57</width>
		<height>13</height>
		<id>72</id>
		<name>Jmeno</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<ent>71</ent>
	</atribute>
	<atribute>
		<left>494</left>
		<top>87</top>
		<width>65</width>
		<height>13</height>
		<id>73</id>
		<name>Prijmeni</name>
		<comment></comment>
		<datatype>VarChar2(20)</datatype>
		<arbitrary>true</arbitrary>
		<ent>71</ent>
	</atribute>
	<atribute>
		<left>626</left>
		<top>80</top>
		<width>29</width>
		<height>13</height>
		<id>74</id>
		<name>rc</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>71</ent>
	</atribute>
	<atribute>
		<left>628</left>
		<top>102</top>
		<width>55</width>
		<height>13</height>
		<id>95</id>
		<name>funkce</name>
		<comment>z_udr, z_pok, z_vet, z_ose</comment>
		<datatype>Char(5)</datatype>
		<arbitrary>true</arbitrary>
		<ent>71</ent>
	</atribute>
	<entity>
		<left>677</left>
		<top>421</top>
		<width>85</width>
		<height>39</height>
		<id>80</id>
		<name>Dodavatel</name>
		<comment></comment>
	</entity>
	<unique>
		<left>788</left>
		<top>445</top>
		<width>10</width>
		<height>10</height>
		<id>84</id>
		<name></name>
		<comment></comment>
		<ent>80</ent>
		<atr>83</atr>
		<primary>true</primary>
	</unique>
	<atribute>
		<left>828</left>
		<top>402</top>
		<width>50</width>
		<height>13</height>
		<id>81</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(30)</datatype>
		<arbitrary>true</arbitrary>
		<ent>80</ent>
	</atribute>
	<atribute>
		<left>828</left>
		<top>425</top>
		<width>58</width>
		<height>13</height>
		<id>82</id>
		<name>adresa</name>
		<comment></comment>
		<datatype>VarChar2(100)</datatype>
		<arbitrary>true</arbitrary>
		<ent>80</ent>
	</atribute>
	<atribute>
		<left>827</left>
		<top>449</top>
		<width>40</width>
		<height>13</height>
		<id>83</id>
		<name>ICO</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>80</ent>
	</atribute>
	<atribute>
		<left>826</left>
		<top>472</top>
		<width>71</width>
		<height>13</height>
		<id>85</id>
		<name>sortiment</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<ent>80</ent>
	</atribute>
	<entity>
		<left>106</left>
		<top>124</top>
		<width>85</width>
		<height>39</height>
		<id>19</id>
		<name>Pavilon</name>
		<comment></comment>
	</entity>
	<unique>
		<left>119</left>
		<top>94</top>
		<width>10</width>
		<height>10</height>
		<id>22</id>
		<name></name>
		<comment></comment>
		<ent>19</ent>
		<atr>20</atr>
		<primary>true</primary>
	</unique>
	<atribute>
		<left>108</left>
		<top>62</top>
		<width>51</width>
		<height>13</height>
		<id>20</id>
		<name>c_pav</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>19</ent>
	</atribute>
	<atribute>
		<left>183</left>
		<top>63</top>
		<width>50</width>
		<height>13</height>
		<id>21</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(40)</datatype>
		<arbitrary>true</arbitrary>
		<ent>19</ent>
	</atribute>
	<entity>
		<left>309</left>
		<top>78</top>
		<width>85</width>
		<height>39</height>
		<id>96</id>
		<name>Udrzuje</name>
		<comment></comment>
	</entity>
	<unique>
		<left>345</left>
		<top>138</top>
		<width>10</width>
		<height>10</height>
		<id>97</id>
		<name></name>
		<comment></comment>
		<ent>96</ent>
		<primary>true</primary>
	</unique>
	<strong>
		<left>145</left>
		<top>174</top>
		<width>4</width>
		<height>4</height>
		<ent>19</ent>
		<uni>41</uni>
	</strong>
	<strong>
		<left>312</left>
		<top>315</top>
		<width>4</width>
		<height>4</height>
		<ent>12</ent>
		<uni>104</uni>
	</strong>
	<entity>
		<left>616</left>
		<top>211</top>
		<width>85</width>
		<height>39</height>
		<id>57</id>
		<name>Prodava</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>717</left>
		<top>137</top>
		<width>103</width>
		<height>13</height>
		<id>59</id>
		<name>datum_prodeje</name>
		<comment></comment>
		<datatype>Date</datatype>
		<arbitrary>true</arbitrary>
		<ent>57</ent>
	</atribute>
	<unique>
		<left>653</left>
		<top>137</top>
		<width>10</width>
		<height>10</height>
		<id>60</id>
		<name></name>
		<comment></comment>
		<ent>57</ent>
		<atr>59</atr>
		<primary>true</primary>
	</unique>
	<entity>
		<left>689</left>
		<top>264</top>
		<width>85</width>
		<height>39</height>
		<id>49</id>
		<name>Vstupenky</name>
		<comment></comment>
	</entity>
	<unique>
		<left>801</left>
		<top>278</top>
		<width>10</width>
		<height>10</height>
		<id>53</id>
		<name></name>
		<comment></comment>
		<ent>49</ent>
		<atr>51</atr>
		<primary>true</primary>
	</unique>
	<atribute>
		<left>825</left>
		<top>249</top>
		<width>46</width>
		<height>13</height>
		<id>50</id>
		<name>cena</name>
		<comment></comment>
		<datatype>Float</datatype>
		<arbitrary>true</arbitrary>
		<ent>49</ent>
	</atribute>
	<atribute>
		<left>826</left>
		<top>278</top>
		<width>34</width>
		<height>13</height>
		<id>51</id>
		<name>typ</name>
		<comment></comment>
		<datatype>VarChar2(40)</datatype>
		<arbitrary>true</arbitrary>
		<ent>49</ent>
	</atribute>
	<entity>
		<left>677</left>
		<top>353</top>
		<width>99</width>
		<height>39</height>
		<id>89</id>
		<name>Zbozi</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>828</left>
		<top>367</top>
		<width>46</width>
		<height>13</height>
		<id>91</id>
		<name>zbozi</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<ent>89</ent>
	</atribute>
	<atribute>
		<left>828</left>
		<top>336</top>
		<width>49</width>
		<height>13</height>
		<id>111</id>
		<name>c_obj</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>89</ent>
	</atribute>
	<unique>
		<left>793</left>
		<top>347</top>
		<width>10</width>
		<height>10</height>
		<id>112</id>
		<name></name>
		<comment></comment>
		<ent>89</ent>
		<atr>111</atr>
		<primary>true</primary>
	</unique>
	<cardinality>
		<left>617</left>
		<top>327</top>
		<width>64</width>
		<height>29</height>
		<id>115</id>
		<name>obj_zbozi</name>
		<comment></comment>
		<ent>89</ent>
		<rel>113</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<cardinality>
		<left>619</left>
		<top>371</top>
		<width>53</width>
		<height>29</height>
		<id>117</id>
		<name>dod_zb</name>
		<comment></comment>
		<ent>89</ent>
		<rel>116</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<cardinality>
		<left>620</left>
		<top>406</top>
		<width>55</width>
		<height>29</height>
		<id>118</id>
		<name>dod_do</name>
		<comment></comment>
		<ent>80</ent>
		<rel>116</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>528</left>
		<top>242</top>
		<width>60</width>
		<height>29</height>
		<id>114</id>
		<name>obj_zam</name>
		<comment></comment>
		<ent>71</ent>
		<rel>113</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<relation>
		<left>505</left>
		<top>299</top>
		<width>119</width>
		<height>39</height>
		<id>113</id>
		<name>objednava</name>
		<comment></comment>
	</relation>
	<relation>
		<left>497</left>
		<top>383</top>
		<width>119</width>
		<height>39</height>
		<id>116</id>
		<name>doda</name>
		<comment></comment>
	</relation>
	<strong>
		<left>513</left>
		<top>263</top>
		<width>4</width>
		<height>4</height>
		<ent>71</ent>
		<uni>105</uni>
	</strong>
</schema>
